### ISSUE TITLE
feathers hooks service issue

### ISSUE THREAD

**Issue by bmangus** [geistinteractive/feathers-filemaker#11]
It appears that the feathers api hooks service has depreciated and removed the disallow method (perhaps among other more substantial changes). As a result the script service in this database adapter is broken. I am attempting to find a fix, but I am new to feathers. Hopefully someone else more familiar can take a look.

**Comment by DelfsEngineering** [comment]
What version of feathers are you using?
There is an upgrade guide that addreses how to upgrade your apps.

I actively use feathers-FileMaker and should be able to help you.
Charles

**Comment by bmangus** [comment]
Thank you for your assistance. I am using feathers v2.2.4. Here is the runtime error:
```
/Users/brianmangus/Desktop/gyp_service/node_modules/feathers-filemaker/lib/script/index.js:37
    RestUtilityService.before(hooks.before);
                       ^

TypeError: RestUtilityService.before is not a function
    at Function.<anonymous> (/Users/brianmangus/Desktop/gyp_service/node_modules/feathers-filemaker/lib/script/index.js:37:24)
    at Function.configure (/Users/brianmangus/Desktop/gyp_service/node_modules/feathers/lib/application.js:150:8)
    at Object.<anonymous> (/Users/brianmangus/Desktop/gyp_service/index.js:22:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by bmangus** [comment]
Correction: I upgraded to feathers v3.1.5, but the error persists. Below is the code from my index.js file. I verified that this code does work without the script service block. It seems to be failing at app.configure. 

```javascript

const feathers = require('@feathersjs/feathers');
const express = require('@feathersjs/express');
const socketio = require('@feathersjs/socketio');
var fms = require('feathers-filemaker');
var script = fms.ScriptService;

const memory = require('feathers-memory');

// Creates an Express compatible Feathers application
const app = express(feathers());

//connection and credentials (local dev server)
const connection = {
  host : '192.168.0.160',
  db : 'ypapp',
  user : 'api',
  pass : 'password',
};

//Begin Script Service
//---configure the script service
app.configure(script({connection, layout: 'web_listings'}));

//---get the service
const ScriptService = app.service('fms-test-GuthrieYP-script');

//---setup endpoint to run the service (test)
app.use('/run', ScriptService.run('test', {paramName1:'paramValue1',paramName2:'paramValue2'}));

//End Script Service


//classifications test
app.use('/classifications', fms({
  connection,
  model :{
    layout : 'test',
    idField : 'zd_ListingID',
  },
  paginate: {
    default: 2,
    max: 4,
  }
}));

//second test
app.use('/class_list', fms({
    connection,
    model:{
        layout: 'web_classifications',
        idField: 'zd_ClassID',
    }
}));



// Start the server.
var port = 3030;

app.listen(port, function() {
  console.log(`Feathers server listening on port ${port}`);
});
```

**Comment by bmangus** [comment]
The hooks service is the culprit. I managed to get it working (for my purposes) by simply commenting out the hooks utility calls in the /lib/script/index.js file. The following is my final code for using it. Slightly different example than in the documentation.

```javascript
//Begin Script Service
//---configure the script service
app.configure(script({connection, layout: 'web_listings', idField: 'zd_recordID'}));

//---get the service
const ScriptService = app.service('fms-GuthrieYP-web_listings-script');

//---setup endpoint to run the service (test)
app.use('/run/:class',
   (req, res, next) => { 
     return ScriptService.run('test', {param: req.params.class})
      .then((data) => { 
        res.send(data) })
      .catch("error"); }
);

//End Script Service
```
